"""add reminders and reminder attempts

Revision ID: 242a55f46528
Revises: b5456329cbdd
Create Date: 2026-07-28 12:11:21.762543

STORY-013 (Production Background Processing, Reminder Engine & Reliable
Job Execution). Three changes, all in this one migration:

1. Creates `reminders` — the durable reminder-delivery queue itself
   (`app.models.reminder.Reminder`). Row-locking concurrency
   (`SELECT ... FOR UPDATE SKIP LOCKED`) is a runtime query pattern
   (`app.repositories.reminder.acquire_pending`), not a schema feature,
   so nothing special is needed here beyond the `ix_reminders_status_scheduled_at`
   index the worker's polling query relies on.
2. Creates `reminder_attempts` — the append-only per-attempt audit trail
   (`app.models.reminder.ReminderAttempt`), referencing `reminders` via a
   composite `(organization_id, reminder_id)` FK.
3. Extends TWO existing CHECK constraints, mirroring the exact bare-
   name-templating technique `5354c755424b`/`b5456329cbdd` already
   established: `workflow_request_type` (on `workflow_runs`) gains
   `reminder_delivery`, and `workflow_event_type` (on `workflow_events`)
   gains `reminder_scheduled`/`reminder_started`/`reminder_sent`/
   `reminder_failed`/`reminder_cancelled` — see
   `app/models/workflow.py`'s `WorkflowRequestType`/`WorkflowEventType`
   docstrings.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "242a55f46528"
down_revision: str | Sequence[str] | None = "b5456329cbdd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_OLD_REQUEST_TYPES = (
    "appointment_booking",
    "appointment_rescheduling",
    "appointment_cancellation",
    "document_collection",
    "administrative_routing",
    "follow_up",
)
_NEW_REQUEST_TYPES = (*_OLD_REQUEST_TYPES, "reminder_delivery")

_OLD_EVENT_TYPES = (
    "workflow_created",
    "workflow_started",
    "step_started",
    "tool_invoked",
    "agent_handoff",
    "step_completed",
    "step_failed",
    "step_skipped",
    "workflow_waiting",
    "workflow_resumed",
    "workflow_completed",
    "workflow_failed",
    "workflow_cancelled",
)
_NEW_EVENT_TYPES = (
    "workflow_created",
    "workflow_started",
    "step_started",
    "tool_invoked",
    "agent_handoff",
    "reminder_scheduled",
    "reminder_started",
    "reminder_sent",
    "reminder_failed",
    "reminder_cancelled",
    "step_completed",
    "step_failed",
    "step_skipped",
    "workflow_waiting",
    "workflow_resumed",
    "workflow_completed",
    "workflow_failed",
    "workflow_cancelled",
)


def _check_sql(column: str, values: tuple[str, ...]) -> str:
    allowed = ", ".join(f"'{value}'" for value in values)
    return f"{column} IN ({allowed})"


def upgrade() -> None:
    """Upgrade schema."""
    # `appointments` never previously needed a unique constraint covering
    # exactly `(organization_id, id)` — nothing referenced it that way
    # until `reminders` (below) does. Purely additive: `id` alone is
    # already the primary key, so this can never fail on existing data.
    op.create_unique_constraint(
        "uq_appointments_organization_id_id", "appointments", ["organization_id", "id"]
    )

    # ### reminders / reminder_attempts tables (autogenerated, reviewed) ###
    op.create_table(
        "reminders",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("appointment_id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("workflow_run_id", sa.Uuid(), nullable=False),
        sa.Column("workflow_step_id", sa.Uuid(), nullable=False),
        sa.Column(
            "reminder_type",
            sa.Enum(
                "appointment_reminder",
                name="reminder_type",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "processing",
                "sent",
                "failed",
                "cancelled",
                name="reminder_status",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("locked_by", sa.String(length=100), nullable=True),
        sa.Column("last_error", sa.String(length=500), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(locked_at IS NULL) = (locked_by IS NULL)",
            name=op.f("ck_reminders_lock_fields_consistent"),
        ),
        sa.CheckConstraint(
            "attempt_count >= 0", name=op.f("ck_reminders_attempt_count_non_negative")
        ),
        sa.CheckConstraint(
            "last_error IS NULL OR length(last_error) <= 500",
            name=op.f("ck_reminders_last_error_length"),
        ),
        sa.CheckConstraint("max_attempts > 0", name=op.f("ck_reminders_max_attempts_positive")),
        sa.CheckConstraint(
            "payload IS NULL OR octet_length(payload::text) <= 2000",
            name=op.f("ck_reminders_payload_size"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "appointment_id"],
            ["appointments.organization_id", "appointments.id"],
            name="fk_reminders_org_appointment_appointments",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "patient_id"],
            ["patients.organization_id", "patients.id"],
            name="fk_reminders_org_patient_patients",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workflow_run_id", "workflow_step_id"],
            [
                "workflow_steps.organization_id",
                "workflow_steps.workflow_run_id",
                "workflow_steps.id",
            ],
            name="fk_reminders_org_run_step_workflow_steps",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workflow_run_id"],
            ["workflow_runs.organization_id", "workflow_runs.id"],
            name="fk_reminders_org_workflow_run_workflow_runs",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_reminders_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reminders")),
        sa.UniqueConstraint("organization_id", "id", name="uq_reminders_organization_id_id"),
    )
    op.create_index(
        op.f("ix_reminders_appointment_id"), "reminders", ["appointment_id"], unique=False
    )
    op.create_index(
        "ix_reminders_org_patient", "reminders", ["organization_id", "patient_id"], unique=False
    )
    op.create_index(
        op.f("ix_reminders_organization_id"), "reminders", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_reminders_patient_id"), "reminders", ["patient_id"], unique=False)
    op.create_index(
        op.f("ix_reminders_scheduled_at"), "reminders", ["scheduled_at"], unique=False
    )
    op.create_index(op.f("ix_reminders_status"), "reminders", ["status"], unique=False)
    op.create_index(
        "ix_reminders_status_scheduled_at", "reminders", ["status", "scheduled_at"], unique=False
    )
    op.create_index(
        op.f("ix_reminders_workflow_run_id"), "reminders", ["workflow_run_id"], unique=False
    )
    op.create_index(
        op.f("ix_reminders_workflow_step_id"), "reminders", ["workflow_step_id"], unique=False
    )
    op.create_table(
        "reminder_attempts",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("reminder_id", sa.Uuid(), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "sent",
                "failed",
                name="reminder_attempt_status",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("provider_name", sa.String(length=100), nullable=False),
        sa.Column("safe_error_message", sa.String(length=500), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "attempt_number > 0", name=op.f("ck_reminder_attempts_attempt_number_positive")
        ),
        sa.CheckConstraint(
            "safe_error_message IS NULL OR length(safe_error_message) <= 500",
            name=op.f("ck_reminder_attempts_safe_error_message_length"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "reminder_id"],
            ["reminders.organization_id", "reminders.id"],
            name="fk_reminder_attempts_org_reminder_reminders",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_reminder_attempts_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reminder_id"],
            ["reminders.id"],
            name=op.f("fk_reminder_attempts_reminder_id_reminders"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reminder_attempts")),
        sa.UniqueConstraint(
            "reminder_id", "attempt_number", name="uq_reminder_attempts_reminder_attempt_number"
        ),
    )
    op.create_index(
        op.f("ix_reminder_attempts_created_at"),
        "reminder_attempts",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reminder_attempts_organization_id"),
        "reminder_attempts",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reminder_attempts_reminder_id"),
        "reminder_attempts",
        ["reminder_id"],
        unique=False,
    )
    op.create_index(
        "ix_reminder_attempts_reminder_id_attempt_number",
        "reminder_attempts",
        ["reminder_id", "attempt_number"],
        unique=False,
    )

    # ### CHECK constraint extensions (bare/short names — see the module docstring) ###
    op.drop_constraint("workflow_request_type", "workflow_runs", type_="check")
    op.create_check_constraint(
        "workflow_request_type",
        "workflow_runs",
        _check_sql("request_type", _NEW_REQUEST_TYPES),
    )
    op.drop_constraint("workflow_event_type", "workflow_events", type_="check")
    op.create_check_constraint(
        "workflow_event_type",
        "workflow_events",
        _check_sql("event_type", _NEW_EVENT_TYPES),
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint("workflow_event_type", "workflow_events", type_="check")
    op.create_check_constraint(
        "workflow_event_type",
        "workflow_events",
        _check_sql("event_type", _OLD_EVENT_TYPES),
    )
    op.drop_constraint("workflow_request_type", "workflow_runs", type_="check")
    op.create_check_constraint(
        "workflow_request_type",
        "workflow_runs",
        _check_sql("request_type", _OLD_REQUEST_TYPES),
    )

    op.drop_index(
        "ix_reminder_attempts_reminder_id_attempt_number", table_name="reminder_attempts"
    )
    op.drop_index(op.f("ix_reminder_attempts_reminder_id"), table_name="reminder_attempts")
    op.drop_index(op.f("ix_reminder_attempts_organization_id"), table_name="reminder_attempts")
    op.drop_index(op.f("ix_reminder_attempts_created_at"), table_name="reminder_attempts")
    op.drop_table("reminder_attempts")
    op.drop_index(op.f("ix_reminders_workflow_step_id"), table_name="reminders")
    op.drop_index(op.f("ix_reminders_workflow_run_id"), table_name="reminders")
    op.drop_index("ix_reminders_status_scheduled_at", table_name="reminders")
    op.drop_index(op.f("ix_reminders_status"), table_name="reminders")
    op.drop_index(op.f("ix_reminders_scheduled_at"), table_name="reminders")
    op.drop_index(op.f("ix_reminders_patient_id"), table_name="reminders")
    op.drop_index(op.f("ix_reminders_organization_id"), table_name="reminders")
    op.drop_index("ix_reminders_org_patient", table_name="reminders")
    op.drop_index(op.f("ix_reminders_appointment_id"), table_name="reminders")
    op.drop_table("reminders")

    op.drop_constraint("uq_appointments_organization_id_id", "appointments", type_="unique")
