"""add workflow event sequence and tool_invoked event type

Revision ID: 5354c755424b
Revises: 291a26a9ce1b
Create Date: 2026-07-27 22:15:17.980676

This migration does two things, both scoped to `workflow_events`:

1. Adds `sequence` — a server-assigned (`GENERATED BY DEFAULT AS
   IDENTITY`), strictly monotonically increasing `BIGINT` column, and
   uses it (via a new index) as the AUTHORITATIVE ordering key for
   reading a workflow's event history. This fixes a genuine flaky-
   ordering bug discovered while validating STORY-010's own
   multi-event-per-request audit trail: two events created in rapid
   succession (exactly what a tool-call event sequence produces) can
   share the same `created_at` value at Python `datetime.now()`
   timestamp resolution, and falling back to `id` (a random UUID) as a
   secondary sort key does not recover insertion order. A
   database-assigned identity column cannot tie between concurrent
   inserts and always reflects true insertion order.
2. Extends the `workflow_event_type` CHECK constraint with one new
   value, `tool_invoked` — see `app/models/workflow.py`'s
   `WorkflowEventType` docstring for why this one addition was judged
   worth the schema change (STORY-010's tool-execution audit trail).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5354c755424b"
down_revision: str | Sequence[str] | None = "291a26a9ce1b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_OLD_EVENT_TYPES = (
    "workflow_created",
    "workflow_started",
    "step_started",
    "step_completed",
    "step_failed",
    "step_skipped",
    "workflow_waiting",
    "workflow_resumed",
    "workflow_completed",
    "workflow_failed",
    "workflow_cancelled",
)
_NEW_EVENT_TYPES = (
    "workflow_created",
    "workflow_started",
    "step_started",
    "tool_invoked",
    "step_completed",
    "step_failed",
    "step_skipped",
    "workflow_waiting",
    "workflow_resumed",
    "workflow_completed",
    "workflow_failed",
    "workflow_cancelled",
)


def _check_sql(values: tuple[str, ...]) -> str:
    allowed = ", ".join(f"'{value}'" for value in values)
    return f"event_type IN ({allowed})"


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "workflow_events",
        sa.Column("sequence", sa.BigInteger(), sa.Identity(always=False), nullable=False),
    )
    op.create_index(
        "ix_workflow_events_run_sequence",
        "workflow_events",
        ["workflow_run_id", "sequence"],
    )
    op.create_unique_constraint(
        op.f("uq_workflow_events_sequence"), "workflow_events", ["sequence"]
    )

    # Bare (short) constraint names below — NOT already prefixed, and NOT
    # wrapped in `op.f()` — so Alembic's naming-convention-aware DDL
    # (`ck_%(table_name)s_%(constraint_name)s`, `migrations/env.py`)
    # templates them to the SAME final name the model's
    # `CheckConstraint(name="workflow_event_type")` already produces:
    # `ck_workflow_events_workflow_event_type`.
    op.drop_constraint("workflow_event_type", "workflow_events", type_="check")
    op.create_check_constraint(
        "workflow_event_type",
        "workflow_events",
        _check_sql(_NEW_EVENT_TYPES),
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint("workflow_event_type", "workflow_events", type_="check")
    op.create_check_constraint(
        "workflow_event_type",
        "workflow_events",
        _check_sql(_OLD_EVENT_TYPES),
    )

    op.drop_constraint(op.f("uq_workflow_events_sequence"), "workflow_events", type_="unique")
    op.drop_index("ix_workflow_events_run_sequence", table_name="workflow_events")
    op.drop_column("workflow_events", "sequence")
